---
title: "Welcome"
author: "Dr. Iris Eekhout"
subtitle: "Workshop name"
date: "`r format(Sys.Date())`"
output: 
  ioslides_presentation:
    logo: Puzzle_zgnb3_m.jpg
    theme: readable
    css: eigencssfile.css
widescreen: true
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Iris Eekhout

PhD project **Don't Miss Out!** | www.missingdata.nl

Personal website: www.iriseekhout.com

GitHub: iriseekhout

**Interests**:

* Missing data methods (multiple imputation)
* Longitudinal (Multilevel) modelling
* R programming/shiny apps
* Psychometrics and measurement



## Missing data analyses | Workshop info

* Missing data analysis
* Missing data methods
* Missing data in practice

* 2-day workshop


## Program | Day 1

**Morning**:
<!----(62 slides)-->
* Lecture 1: Missing data analyses  
  + What are missing data, why do we have missing data
	+ What kind of missing data are there
	+ What are missing data mechanisms
	+ How can we investigate our missing data

* Practical 1: Missing data analyses 

## Program | Day 1

**Afternoon**:
<!----(22 slides ad hoc; 53 slides MI + methods)-->
* Lecture 2: Dealing with missing data 
	+ Ad hoc solutions and what's wrong with that?
	+ Multiple imputation - how does it work
	+ Overview of imputation methods
	
* Software demo: How to perform multiple imputation with MICE 

* Practical 2: Dealing with missing data


## Program | Day 2

**Morning**:
<!----(13 slides FIML 17 slides longitudinal )-->
* Lecture 3: Missing data in practice
	+ Full information maximum likelihood
	+ Missing data in questionnaires
	+ Missing data in longitudinal designs

* Practical 3: Missing data in practice
	+ Discuss practical issues of participants.


## Suggested literature

* Website about missing data: www.missingdata.nl
* Flexible Imputation of Missing Data (Stef van Buuren): https://stefvanbuuren.name/fimd/
* Applied missing data analysis with SPSS and R (Martijn Heymans & Iris Eekhout) *draft version*: https://bookdown.org/mwheymans/bookmi/


## Most important `R` packages

For missing data handling:

* `mice`: multiple imputation by chained equations
* `miceadds`: additional Multiple Imputation Functions, Especially for 'mice'

Other R packages

* `dplyr`: for data manipulation, summarizing and grouping
* `tidyr`: tools for shaping and structuring data.