---
title: "Missing data analysis"
author: "Iris Eekhout"
date: "2-3-2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
##preparation for post on website: www.iriseekhout.nl and to be used in workshop.

library(dplyr)
library(tidyr)
```

Missing observations are defined as `NA` in R. Missing data can have different implications for data summaries, analyses and conclusions based on the data with missing observations. In this post, different types of missing data are reviewed and explored in some data examples.

In the example data that is generated with the `mvrnorm` function from the `MASS` package, there are missings created with the  `MCAR` function from the `dmo` package. The missings are created completely at random. 


```{R}
#example data 
cov <- matrix(c(rep(0.7, 25)), nrow = 5)
diag(cov) <- 1
dat <- MASS::mvrnorm(n = 25, rep(0,5), Sigma = cov)

patterns <- matrix(c(0,1,1,0,0,
                     1,0,1,1,0), nrow = 2)
datm <- dmo::MCAR(data.frame(dat), alpha = 0.50, pattern = patterns, f = c(0.5, 0.5))
datm
```


## Explore the amount of missing data

The amount of missing data can be expressed from different points of views. We can count the number of missing entries in the entire data by using the `is.na` function. In total there are `r sum(is.na(datm))` missing data entries. The data frame contains 5 variables for 25 subjects, which makes a total of 125 data entries. Accordingly, `r sum(is.na(datm))/length(is.na(datm)) *100`% of the data entries are missing.  

```{R}
sum(is.na(datm))

sum(is.na(datm))/length(is.na(datm)) * 100

```

Another way is to look at the amount of missing data, is to summarize the missing observations per variable. For each variable we can count the number of missing observations (n) and calculate the proportion (p)

```{R}

datm %>%
  is.na %>%
  data.frame() %>%
  summarise_all(list(n = sum, p = mean)) %>%
  pivot_longer(everything(), 
               names_to = c("variable", ".value"),
               names_pattern = "(.*)_(.)")

```




## Missing data patterns



