---
title: "Workshop missing data"
author: "dr. Iris Eekhout"
date: "Zurich - 27 & 28 June 2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Workshop summary

Missing data are an issue in many types of studies and in many fields of research. Missing data can seriously hamper analysis results and bias study conclusions. For that reason it is important to use a good strategy to deal with missing data. Using a missing data method that fits with the missing data problem and envisioned analysis enhances the quality of the substantive analysis results.
This workshop hold three major parts: missing data analysis, missing data methods and missing data in practice. The first part about missing data analysis is centered around the following questions: What are missing data? How can I investigate the missing data? What are missing data mechanisms? How can I evaluate the missing data mechanism? In the second part, ad hoc methods to deal with missing data are outlined, followed by a thorough account of the more advanced strategy to deal with missing data: multiple imputation. The third part of the workshop involves missing data in practice where full information maximum likelihood, strategies to deal with missing data in questionnaires and methods for longitudinal missing data are reviewed. 
Each part of the workshop involves a lecture that has a practical focus and is aimed to provide the necessary understanding of the methodology to enable participants to use the methods in practice. After each lecture, practical assignments are available to get more familiar with the material and apply the learned missing data strategies and methods. For the missing data in practice part, participants are welcome to bring their own missing data problems into the workshop.  


## Program

### Day 1 - morning: 

* Lecture 1: Missing data analyses
  + What are missing data, why do we have missing data?
  + How can I investigate the missing data?
  + What are missing data mechanisms?
  + How can I evaluate the missing data mechanism?

* Practical 1: Missing data analyses

### Day 1 - afternoon: 

* Lecture 2: Dealing with missing data
  + Ad hoc solutions and what's wrong with that?
  + Multiple imputation - how does it work
  + Overview of imputation methods

* Software demo: How to perform multiple imputation with `mice`
* Practical 2: Multiple imputation

### Day 2 - morning: 

* Lecture 3: Missing data in practice 
  + Full information maximum likelihood
  + Missing data in questionnaires
  + Missing data in longitudinal designs

* Practical 3: Missing data in practice
  + Discuss practical issues of participants
